name: Seeker

on:
  schedule:
    - cron: '17 */12 * * *'
  workflow_dispatch:

jobs:

  seek:
    runs-on: ubuntu-latest
    container:
      image: archlinux
    env:
      CACTUS_CONFIG: ${{ secrets.CACTUS_CONFIG }}

    steps:
      - uses: arch4edu/cactus/actions/upgrade-archlinux@main
        id: init

      - name: Install runtime dependencies
        run: pacman -S --noconfirm --needed nvchecker python-mysqlclient

      - uses: arch4edu/cactus/actions/setup-cactus@main

      - name: Set up nvchecker cache
        uses: actions/cache@master
        with:
          path: nvchecker
          key: nvchecker-${{ steps.init.outputs.time }}
          restore-keys: nvchecker-

      - uses: arch4edu/cactus/actions/checkout-repository@main

      - name: Collecting cactus.yaml
        run: python -m cactus.seeker.collect repository

      - name: Run nvchecker
        run: |
          mkdir -p nvchecker
          [ -f nvchecker/newver.json ] && mv nvchecker/newver.json nvchecker/oldver.json
          nvchecker --logger both -c nvchecker.toml | tee nvchecker.log

      - name: Update database
        run: python -m cactus.seeker.update repository
